services:
  backend:
    build:
      context: ./Backend
    command: gunicorn --bind 0.0.0.0:5003 --workers 1 --threads 4 --timeout 300 --reload server:app
    ports:
      - "5003:5003"
    volumes:
      - ./Backend:/app/Backend
      - ./Example_Data:/app/Example_Data
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
